export const GET_USERS = "GET_USERS";

export const CURRENT_USER_LOGIN = "CURRENT_USER_LOGIN";
export const CURRENT_USER_LOGOUT = "CURRENT_USER_LOGOUT";

export const GET_CATEGORIZED_QUESTIONS_OF_USER = "GET_CATEGORIZED_QUESTIONS_OF_USER";

export const SAVE_QUESTION = "SAVE_QUESTION";
export const SAVE_QUESTION_ANSWER = "SAVE_QUESTION_ANSWER";

export const GET_PARTICULAR_QUESTION = "GET_PARTICULAR_QUESTION";